language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - yarn add $TYPESCRIPT
  - yarn build

env:
  - TYPESCRIPT=typescript@3.2.2
  - TYPESCRIPT=typescript@3.1.6
  - TYPESCRIPT=typescript@3.0.3
  - TYPESCRIPT=typescript@2.9.2
  - TYPESCRIPT=typescript@2.8.4
  - TYPESCRIPT=typescript@2.7.2
  - TYPESCRIPT=typescript@2.6.2
  - TYPESCRIPT=typescript@2.5.3
  - TYPESCRIPT=typescript@2.4.2

node_js:
  - "8"
  - "10"
  - "11"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
