language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - yarn add $TYPESCRIPT
  - npm run test-on-travis

env:
  - TYPESCRIPT=typescript@latest
  - TYPESCRIPT=typescript@2.5.3
  - TYPESCRIPT=typescript@2.4.2
  - TYPESCRIPT=typescript@2.3.4
  - TYPESCRIPT=typescript@2.2.2

node_js:
  - "6"
  - "7"
  - "8"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
