language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - npm install $TYPESCRIPT --force
  - npm run test-on-travis

env:
  - TYPESCRIPT=typescript@2.0.0
  - TYPESCRIPT=typescript@2.0.2
  - TYPESCRIPT=typescript@2.0.3
  - TYPESCRIPT=typescript@2.0.6
  - TYPESCRIPT=typescript@2.0.7
  - TYPESCRIPT=typescript@2.0.8
  - TYPESCRIPT=typescript@2.0.9
  - TYPESCRIPT=typescript@2.0.10
  - TYPESCRIPT=typescript@2.1.1
  - TYPESCRIPT=typescript@2.1.4
  - TYPESCRIPT=typescript@2.1.5
  - TYPESCRIPT=typescript@2.1.6
  - TYPESCRIPT=typescript@2.2.0
  - TYPESCRIPT=typescript@2.2.1
  - TYPESCRIPT=typescript@2.2.2
  - TYPESCRIPT=typescript@2.3.0
  - TYPESCRIPT=typescript@latest

node_js:
  - "6"
  - "7"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
