language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - npm install
  - npm install $TYPESCRIPT --force
  - npm run test-on-travis

env:
  - TYPESCRIPT=typescript@2.8.4
  - TYPESCRIPT=typescript@2.7.2
  - TYPESCRIPT=typescript@2.6.2
  - TYPESCRIPT=typescript@2.5.3
  - TYPESCRIPT=typescript@2.4.2
  - TYPESCRIPT=typescript@2.3.4

node_js:
  - "6"
  - "7"
  - "8"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
