language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - npm install $TYPESCRIPT --force
  - npm run test-on-travis

env:
  - TYPESCRIPT=typescript@latest

node_js:
  - "6"
  - "7"
  - "8"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
