language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - '18'
  - '20'
  - '22'
  - '24'

env:
  - TS=typescript@5.8.3
  - TS=typescript@5.7.2
  - TS=typescript@5.6.3
  - TS=typescript@5.5.4
  - TS=typescript@5.4.5
  - TS=typescript@5.3.3
  - TS=typescript@5.2.2
  - TS=typescript@5.1.6
  - TS=typescript@5.0.4

# NOTE: do not include @types/node to this project, because
# @types/node:    interface IteratorResult<T> { };
# typescript:     type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
# tsc error:      TS2300: Duplicate identifier 'IteratorResult'.

 before_install:
  - export NV=`node -v | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'`

install:
  - npm i -g ts-node@8 nyc@15
  - npm i jasmine@3.5.0 @types/jasmine@3.5.0 @types/node@${NV} ${TS}

script:
  - yarn run build
  - yarn run test:coverage

after_script:
  - npm i coveralls@2
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
