import { IAttribute } from './attribute';

/**
 * Access and store attribute and metadata for reflection
 */
export abstract class Decoratable {

  private _attributes: Array<IAttribute> = [];
  private _metadata: Map<string, any>;
  private _hasInterceptor: boolean;
  private _hasInitializer: boolean;

  /**
   * Add an attribute
   * @param {IAttribute} attribute
   */
  addAttribute(attribute: IAttribute): void {
    if (!attribute) {
      throw new TypeError(`Unable to add null attribute`);
    }
    this._attributes.push(attribute);
    // if the attribute provide a getInterceptor, that means this property may need inject
    // we don't call getInterceptor or getInitializer until user new() the agent class.
    if (!!attribute.getInterceptor) {
      this._hasInterceptor = true;
    }
    if (!!attribute.getInitializer) {
      this._hasInitializer = true;
    }
  }

  /**
   * Return an array of attributes which is instance of giving type
   * @returns {IAttribute[]}
   */
  getAttributes<T extends IAttribute>(type?): T[] {
    if (type) {
      return this._attributes.filter(a => a instanceof type) as Array<T>;
    }
    else {
      return this._attributes.slice(0) as Array<T>;
    }
  }

  /**
   * Return true if this type contains a giving attribute, otherwise false.
   * @param type
   * @returns {boolean}
   */
  hasAttribute<T extends IAttribute>(type?): boolean {
    if (type) {
      return this._attributes.some(a => a instanceof type);
    }
    else {
      return !!this._attributes.length;
    }
  }

  /**
   * Return an array of all the attributes which provide getInterceptor method
   * @returns {IAttribute[]}
   */
  getInterceptors(): IAttribute[] {
    return this._attributes.filter(a => a.getInterceptor);
  }

  /**
   * Return an array of all the attributes which provide getInitializer method
   * @returns {IAttribute[]}
   */
  getInitializers(): IAttribute[] {
    return this._attributes.filter(a => a.getInitializer);
  }

  /**
   * Return true if any of the attribute provide getInterceptor method
   * @returns {boolean}
   */
  hasInterceptors(): boolean {
    return this._hasInterceptor;
  }

  /**
   * Return true if any of the attribute provide getInitializer method
   * @returns {boolean}
   */
  hasInitializer(): boolean {
    return this._hasInitializer;
  }

  /**
   * Read the metadata generated by tsc
   * @param {string} key
   * @returns {any}
   */
  getMetadata(key: string): any | null {
    if (!this._metadata) {
      return null;
    }
    return this._metadata.get(key);
  }

  /**
   * Add the metadata generated by tsc
   * @param {string} key
   * @param value
   */
  addMetadata(key: string, value: any) {
    if (!this._metadata) {
      this._metadata = new Map<string, any>();
    }
    this._metadata.set(key, value);
  }

}
