name: Coveralls

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  test-node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [16]
        ts: [4.3.5]
      fail-fast: false
      max-parallel: 6
    name: ${{ matrix.os }}, Node.js ${{ matrix.node }}, TS ${{ matrix.ts }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm i -g ts-node@8 nyc@15 typescript@${{ matrix.ts }}
      - run: npm i jasmine@3.5.0 @types/jasmine@3.5.0 @types/node@${{ matrix.node }} typescript@${{ matrix.ts }}
      - run: npm run build
      - run: npm run test:coverage
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
