name: Windows 2022 Tests

on: [push]

jobs:
  test-node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        node: [24, 22, 20, 18, 16, 14, 12, 10, 8]
        ts: [5.8.3, 5.7.2, 5.6.3, 5.5.4, 5.4.5, 5.3.3, 5.2.2, 5.1.6, 5.0.4]
      fail-fast: false
      max-parallel: 8
    name: ${{ matrix.os }}, Node.js ${{ matrix.node }}, TS ${{ matrix.ts }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm i -g ts-node@8 nyc@15 typescript@${{ matrix.ts }}
      - run: npm i jasmine@3.5.0 @types/jasmine@3.5.0 typescript@${{ matrix.ts }}
      - run: npm run build
      - run: npm run test
